name: Build inPaws (Windows)

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install MSYS2 / MinGW (opcional)
      run: |
        choco install mingw

    - name: Build
      run: |
        make

    - name: Create artifact
      if: github.event_name != 'release'
      uses: actions/upload-artifact@v4
      with:
        name: inpaws-windows
        path: inpaws.exe

    - name: Upload to release
      if: github.event_name == 'release'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: inpaws.exe
        tag: ${{ github.ref }}
        overwrite: true
